title: sphinx tutorial
description: A step-by-step tutorial for documentation generation with sphinx

remote_theme: just-the-docs/just-the-docs

heading_anchors: true

aux_links:
  "Example project":
    - "//github.com/aelsayed95/the-office"
aux_links_new_tab: true

back_to_top: true
back_to_top_text: "Back to top"

callouts:
  tip:
    title: Tip
    color: purple
  hint:
    title: Hint
    color: green
    opacity: 0.1
